### ISSUE TITLE
CPT-onomies term cache is invalid from WP4.7

### ISSUE THREAD

**Issue by petersuba** [bamadesigner/cpt-onomies#26]
As discussed under #25 

I get error notices when WP_DEBUG is on. Specifically I get these two lines:
`PHP Notice: Trying to get property of non-object in /[basedir]/public_html/wp-includes/post.php on line 6073 
PHP Notice: Trying to get property of non-object in /[basedir]/public_html/wp-includes/post.php on line 6074`

This happens every time a line of code touches a post which has a linked CPT-onomy. So for example if a query includes 3 posts which have been linked to a custom post type, I get 3 of these on get_posts(). Then, I get 2 of these each time I do a get_the_excerpt() for a post that has a linked CPT-onomy.

The above referenced lines in post.php are within the function wp_queue_posts_for_term_meta_lazyload(), and specifically as it tries to iterate an array created on the back of calling
`get_object_term_cache('$post->ID, $taxonomy ');`

So it looks to me like there is potentially as mess created with regards to the cache.

additional info copied here from @socki03

> I believe you have stumbled onto a whole new issue dealing with the term cache. I just did a quick var_dump on the cached terms, and all my CPT-onomies are showing up as an array full of NULL variables.

**Comment by Ciantic** [comment]
I've looked a slightly into this, here is the part where WordPress populates the cache:

https://core.trac.wordpress.org/browser/tags/4.7.1/src/wp-includes/category-template.php#L1159

```
	                $terms = wp_get_object_terms( $post->ID, $taxonomy );
	                if ( ! is_wp_error( $terms ) ) {
	                        $term_ids = wp_list_pluck( $terms, 'term_id' );
	                        wp_cache_add( $post->ID, $term_ids, $taxonomy . '_relationships' );
	                }
```

If that is putting nulls there, it must be something wrong with [get_object_terms filter]() which is called by the wp_get_object_terms.

**Comment by elvismdev** [comment]
Hi, 

I have been tracing this down trough all the functions/methods that works behind the [`get_object_term_cache` call on post.php](https://core.trac.wordpress.org/browser/tags/4.7.2/src/wp-includes/post.php#L6070) and I can confirm it ends up querying the DB using the [WP_Term](https://core.trac.wordpress.org/browser/tags/4.7.2/src/wp-includes/class-wp-term.php#L15) class to look for the CPT-onomies. 

From my perspective this is wrong since this class work is to query the `wp_terms` and `wp_term_taxonomy` tables but, on this case CPT-onomies should query the `wp_post` to look for Custom Post Types treating them as Taxonomies. 

This means CPT-onomies need some good code fixing on that area, because seems like it is not passing trough the filters it adds to provide CPT's as Taxonomies. 

If anyone else wants to take it from here, on [`class-wp-term.php` line 140](https://core.trac.wordpress.org/browser/tags/4.7.2/src/wp-includes/class-wp-term.php#L140) from the [`get_instance()` method](https://core.trac.wordpress.org/browser/tags/4.7.2/src/wp-includes/class-wp-term.php#L125) is exactly where it fails returning `false` because it didn't found any `$terms`, since the parameters given to [`get_instance()`](https://core.trac.wordpress.org/browser/tags/4.7.2/src/wp-includes/class-wp-term.php#L125) were actually a CPT `id` and a CPT `slug`, instead a Taxonomy `id` and  `slug` which is what this method actually expects. 

That, get's converted later into a `null` value on [`taxonomy.php` line 749](https://core.trac.wordpress.org/browser/tags/4.7.2/src/wp-includes/taxonomy.php#L749) resulting after in the _array full of NULL variables_ that @socki03 mentions:

> I believe you have stumbled onto a whole new issue dealing with the term cache. I just did a quick var_dump on the cached terms, and all my CPT-onomies are showing up as an array full of NULL variables.


Hope this info helps someone to dig more and send a PR with a possible fix.

Looking forward if @bamadesigner can have this patched promptly.

**Comment by jalefkowit** [comment]
Just chiming in to confirm that I've run into this issue too, using the latest version of CPT-onomies (1.3.6). In my case calls to get_the_term_list() and get_the_terms() that were supposed to be returning results from a CPT-onomy were instead returning tags that happened to have the same term_id in the tag taxonomy as the relevant post IDs from the the CPT-onomy. Switching those calls to use wp_get_object_terms() (which bypasses WP's internal term cache) returned the correct results, so it's got to be _something_ related to how CPT-onomies interacts with that cache.

I tried to run it down further from there, but got lost in the weeds of how that cache actually works -- the WP documentation could be a lot clearer on that subject. So I'll have to circle back later and see if I can figure it out.

**Comment by bruno-rodrigues** [comment]
Log files are becoming HUGE because of this bug.. :(

**Comment by petersuba** [comment]
Just to add that I suspect I now have further complications where the root cause is the issue to do with the cache being populated with NULLs. I have several other plugins that seem to start to throw exceptions, errors and warnings where they are working with various post terms and not expecting NULLs. E.g. 
Posts in Sidebar was throwing an error ` PHP Catchable fatal error:  Object of class WP_Error could not be converted to string in /[rootdir]/public_html/wp-content/plugins/posts-in-sidebar/inc/pis-functions.php on line 1078` whenever it was working on a Post that had a CPT-onomy attached.  I have patched it up [https://github.com/aldolat/posts-in-sidebar/pull/33](url) but it looks like I have some further warnings as well.

E.g. `PHP Warning:  Invalid argument supplied for foreach() in /home/wessexoc/public_html/wp-content/plugins/event-organiser/includes/event-organiser-cpt.php on line 789` where it is a foreach statement expecting to iterate a terms array. I don't have time to fully debug this one but seems pretty likely it has its roots in this same fundamental issue.

**Comment by fleiflei** [comment]
I found a quick and dirty work around that prevents these warning messages from popping up but might have an impact on the performance of the site. 

I found that the problem only occurs while preparing lazy loading of term data... in wp core function get_posts() of class WP_Query the respective code is started UNLESS the query parameter "lazy_load_term_meta" is false. Thus using the 'pre_get_posts' action we can set this parameter to fase, i.e.:

```
function disable_term_lazyloading_with_cpt_onomies($query) {
    if (class_exists('CPT_TAXONOMY')) { //only use while CPT-onomies is installed
        $query->query_vars['lazy_load_term_meta'] = false;
    }
    return $query;
}

add_action('pre_get_posts', 'disable_term_lazyloading_with_cpt_onomies');
```

I suppose for small sites the impact on performance should be neglectable. I have not tested this with larger sites with many taxonomies, terms and posts...

And of course this is not a real solution to the problem.

I haven't looked much deeper into the code of CPT-onomy but another approach could be to create the cache entries for CPT-onomies manually before WP checks for them and tries to create them itself (function `wp_queue_posts_for_term_meta_lazyload`).

**Comment by socki03** [comment]
I believe I have figured out what the issue here is.  I wrote a function that would potentially fix the object caches on any post that gets loaded, but I am still running into issues.  The caches are updating correctly, and storing the CPT IDs as the term_ids, but the function `get_object_term_cache()` in taxonomy.php runs a verification on all the terms pulled out of the cache to make sure they still exist, by running `get_term` on each term ID pulled from the cache.

Here's where the problem lies, because `get_term` runs, and doesn't run through the CPT_ONOMY class created by the plugin, it has a falling out right here:

	if ( is_wp_error( $_term ) ) {`
		return $_term;
	} elseif ( ! $_term ) {
		return null;
	}

It's checking the $_term variable before apply_filters are run which should load our normal term through CPT-onomies, and since the term is false by WP's usual check, it's always returning null.  So, even if the cache is updated, I was STILL getting an array full of nulls.

Anyway, the bottom line is, it's not a problem that's easily fixable through some plugin fixing, it's a core issue, and I've submitted a ticket here: https://core.trac.wordpress.org/ticket/42361#ticket

There's still something that needs to be done about the object caches, and I have some code written, like I said, but it doesn't do any good until core gets updated.

I'll keep this thread posted if my ticket gets updated.

**Comment by raffjones** [comment]
Just to confirm I'm seeing this issue. Have to abandon using the plugin for now which is a shame - it worked nicely on a previous project.

**Comment by fearlex** [comment]
I inherited a whole multisite project which is using this plugin on one of the sites to populate a whole lot of information together with ACF. Having the debug.log enabled eventually fills the server disk because of this notice showing constantly.

![cleanshot 2018-12-26 at 10 03 54](https://user-images.githubusercontent.com/89010/50449484-ad5be000-08f5-11e9-8abb-1f81157ca6c7.png)

This issue has been opened for 2 years now. Is there any solution or workaround to this?

**Comment by bamadesigner** [comment]
Sorry. CPT-onomies has been adopted and is being worked on by another developer. I'd post in the main WordPress Support forum to reach out to them. Thanks!
